kind = "web"
previewPath = "/"
title = "Genesis Nieto Portfolio"
version = "1.0.0"
id = "artifacts/genesis-portfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 24355
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/genesis-portfolio run dev"

[services.env]
PORT = "24355"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/genesis-portfolio", "run", "build"]
publicDir = "artifacts/genesis-portfolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
