import { motion } from "framer-motion";
import { Button } from "./ui/button";

export function Hero() {
  const scrollTo = (id: string) => {
    document.querySelector(id)?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <section id="hero" className="relative min-h-[100svh] flex items-center justify-center overflow-hidden pt-20">
      {/* Background Image generated by agent */}
      <div className="absolute inset-0 z-0">
        <img
          src={`${import.meta.env.BASE_URL}images/hero-bg.png`}
          alt="Abstract elegant background"
          className="w-full h-full object-cover opacity-80"
        />
        {/* Subtle gradient overlay to ensure text readability */}
        <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-transparent to-background" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.2 }}
        >
          <span className="inline-block glass px-4 py-1.5 rounded-full text-sm font-medium tracking-widest uppercase mb-8 text-foreground/80">
            UGC Creator · Fitness Coach · Lifestyle
          </span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.4 }}
          className="text-6xl md:text-8xl lg:text-9xl font-heading text-foreground mb-6"
        >
          Génesis Nieto
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="text-lg md:text-xl text-foreground/80 max-w-2xl mx-auto mb-8 font-light leading-relaxed text-balance"
        >
          Entrenadora y creadora de contenido apasionada por el bienestar. Fusiono la estética del estilo de vida con la disciplina del fitness y el placer de las recetas saludables.
        </motion.p>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.8 }}
          className="text-xl md:text-2xl font-heading italic text-foreground max-w-3xl mx-auto mb-12 text-balance"
        >
          "No solo grabo contenido; capturo la experiencia real de tu marca para conectar con personas reales."
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 1 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Button onClick={() => scrollTo('#servicios')} size="lg">
            Ver Servicios
          </Button>
          <Button onClick={() => scrollTo('#contacto')} variant="glass" size="lg">
            Contactar
          </Button>
        </motion.div>
      </div>
    </section>
  );
}
